### ISSUE TITLE
Ghetto problem selection in contest admin

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#124]
![](https://sc-cdn.scaleengine.net/i/0f182c3beca5f4222cb92d40c67496c9.png)

**Comment by quantum5** [comment]
I remain unconvinced that it is a good idea to allow you to actually swap the problems. This breaks `ContestSubmission` since it links both `ContestProblem` and `Submission`, and it would be insane to change the problem. I am convinced the actual solution is to have an order field. Let me see if `django-suit` has some nice up/down controls like we have for navigation admin.

**Comment by FatalEagle** [comment]
@quantum5 Sounds like an ever better idea.

**Comment by quantum5** [comment]
I don't think there is really anything more to this.

**Comment by Xyene** [comment]
Column headers are incorrect.

![](https://sc-cdn.scaleengine.net/i/e88669ef9c43436cad590c85d02b93361.png)

**Comment by quantum5** [comment]
Not because of the changes here.
