### ISSUE TITLE
Custom Language Limits still show global limit for TLE

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#131]

**Comment by quantum5** [comment]
A technically correct but ridiculous fix would be to show the custom language limit only if it's less than the normal limit.

Actually, a better solution is to just say `> 0.000s` for all TLEs. :p Still, the case that resulted in this issue is technically correct because the submission did ran for more than 2 seconds.

**Comment by FatalEagle** [comment]
Technically yes, but it may be misleading since historically we have used `> TL`, which leads users to think that `TL` is the same as language limit TL.
