### ISSUE TITLE
Disable _ italicization

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#188]
`_` is used a lot in code and LaTeX. Currently, our markdown setup convert `_` to italics. This calls for massively unnatural way of writing `\_`, which bothers me greater. Propose to disable this "feature".

**Comment by Xyene** [comment]
I'm tempted to declare this issue closed, as I've made it so that `_you can do this_` to italicize as well as `~X_i~` for LaTeX. The best of both worlds! Alas, a confession: I have no idea what causes this behaviour. My commit should've removed _-wrapped italics, but instead it just "fixed" LaTeX subscripts.

Reopen if the world burns down to ashes.
