### ISSUE TITLE
Space between sidebar and hover links

### ISSUE THREAD

**Issue by kobortor** [DMOJ/site#251]
http://imgur.com/l1rGsBN

Can't click the links on the side without them disappearing

**Comment by Xyene** [comment]
#205 

The style of the submenu should be

```css
#navigation ul li ul {
    bottom: auto;
    left: 7.55em;
    top: auto;
    margin-top: -38px;
```

To be honest I'm not sure where the magic value of `7.55em` comes from (just played around with it in the style editor until it looked fine), but it was `8em` prior to the theme modernization. @quantum5 how's your memory?

Aside from that, another small bug: the width of the `ul` tag should not be set to `8em`, but rather autosized to the navbar items.

**Comment by quantum5** [comment]
Why `8em`? Because it happened to work back then. `em` is slightly more flexible than `px`.

Actual fix that respects the width of navbar elements is `$('#navigation ul li ul').css('left', $('#nav-list').width())`, and this is not THAT bad because the mobile navbar only works with JS. You have to click on the `MENU`, which is handled by JS.
