### ISSUE TITLE
Pretests

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#279]
To prevent cheating, we will use pretest - systest model for DMOPC. Therefore, the pretest system needs to be improved a little.

Suggested Improvements:
- Add a pretests field to problems. When checked, it will tell the judge to run pretests only.
- Instead of AC, the status code should be PP (Pretests Passed) or [AC?],  all other codes remain the same. It's better to not display a numerical score, but 0/0 is not too bad.
- Display a warning message about "pretests passed does not guarantee system tests will pass".

**Comment by FatalEagle** [comment]
This issue is more serious than one might think, as normally pretests are short circuited.

**Comment by WallE256** [comment]
All the tests should be calculated from the beginning, and only a few test result should be shown. This should be configurable in init.json.

**Comment by FatalEagle** [comment]
You also have to deal with the fact that the judge should give extra information like (your submission got runtime error on final tests, the next submission starts running already) or (your submission TLE'd on final tests, there is a long queue of submissions waiting).

**Comment by WallE256** [comment]
The actual judge gives all the info, but it's filtered by the web interface. Or maybe, at the finish of the contests, all the submissions will be rejudged with all the tests.

**Comment by FatalEagle** [comment]
Currently rejudging all submissions is the popular idea, since for the judge to provide all the info it must spend time running all the tests. However, pretests are short-circuited by default, so the init.json during the contest will differ substantially from the init.json after the contest (also, it will not say Pretests if the point value is not 0).

**Comment by Xyene** [comment]
We can add a `run_pretests_only` field in the `Contest` model, and when rejudging a `Submission` related to a `ContestSubmission`, pass the value of the parent contest's `run_pretests_only` as a new parameter to the judge.

Since the judge has recently been refactored, this should be simple to do judge-side.

If we implement it, we should probably go a step further:
* add a `is_pretest` `BooleanField` to the `Submission` model; we currently use 0 point cases to determine pretests, but this would allow pretests to count for points during contests (and not, post-contest? not run pretests for non-contest at all? @FatalEagle, thoughts on this?).
* add a dedicated `pretest_test_cases` node to `init.yml` that behaves just like `test_cases`, but is used only for pretests.

Doing this should make running pretested contests less of a hassle, for sure. We might even be able to display pretest-specific info as previously mentioned.

/cc @quantum5 @FatalEagle @WallE256

**Comment by quantum5** [comment]
It certainly is the simplest way to implement pretests, simply delegating to judge side. However, your accusation in #417 would apply.

**Comment by Xyene** [comment]
This has been implemented.

![image](https://cloud.githubusercontent.com/assets/1403503/17314990/45be6fa2-5836-11e6-9f7f-dbc9c15c6ab8.png)

**Comment by Xyene** [comment]
The current implementation is wrong.

Problems that don't actually have pretests defined show the same "Pretest Execution Results" since it's based on whether the contest is pretested. A fix requires the judge to reply whether it has pretest cases in `grading-begin-packet`, and set `is_pretest` accordingly when received.

**Comment by quantum5** [comment]
Great, more protocol changes!

**Comment by Xyene** [comment]
This has now been resolved.
