### ISSUE TITLE
Wordpress Admin Theme

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#333]
`django-wpadmin` looks really good on DMOJ. We can probably fork it for our own purposes, to add a few actually good parts of `django-suit`. This would probably allow #308 to be fixed as well.

@Xyene please don't hijack #326

**Comment by Xyene** [comment]
It does look very nice:

![](https://sc-cdn.scaleengine.net/i/82c139f724407ff07ffaf053e30580eb.png)

Loads much faster too.

**Comment by Xyene** [comment]
A couple of issues:

* Font for textboxes is terrible (~ looks like -, among other things)
* select2 doesn't always work (perhaps #308 will fix it)
* Allowed languages field is squished to 1 char width

**Comment by Xyene** [comment]
A 1.9.x fork of django-wpadmin: <https://github.com/kangfend/django-wpadmin/tree/1.9.x>

**Comment by Xyene** [comment]
We should use a FontAwesome specified in settings instead of loading a separate one just for the admin site (saves 100kb, out of a total page size of ~1mb).

**Comment by Xyene** [comment]
The admin interface has seen progressive improvements since this issue was created, and is quite usable (and *really nice to use*). Off the top of my head, I can't think of any issues with the admin interface that would be relevant to this ticket (even the issue of select2 problems was resolved by @quantum5 yesterday), so I'm closing this.
