### ISSUE TITLE
Store the judge that graded a submission

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#373]
@Xyene suggested `on_acknowledge` as the place to set the judge.

**Comment by Xyene** [comment]
On the frontend, this should probably be displayed in the top right corner of a submission page, next to admin links. However, this would require a more fancy Ajax on rejudge.

**Comment by quantum5** [comment]
I am sure we can simply send the judge name in the event packet.

**Comment by Xyene** [comment]
That potentially leaks the judge name to a user, which may not be ideal (though it may not really matter).

**Comment by quantum5** [comment]
The user can see all the judge names anyway.

**Comment by quantum5** [comment]
It is... unwise for `makemigrations` to anger me. Angry Quantum is not a pleasant sight.

**Comment by quantum5** [comment]
@Xyene all the database portion is done.

**Comment by Xyene** [comment]
This is done, though it requires a page reload for active submissions that receive a judge acknowledgement while the page is open. This could be Ajax'd, but it's really not worth the effort.

**Comment by quantum5** [comment]
What do you mean not worth the effort? Simply send judge name in the event packet.

**Comment by Xyene** [comment]
If you want to do it, by all means go ahead.

At the same time, it would potentially leak the grading judge to users - since we don't display that info publicly, this may not be ideal as it may encourage mass resubmitting (especially since it would be easy to write a user-script to intercept the judge name even for unauthorized users).
