### ISSUE TITLE
POST submit requests are unchecked

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#403]
A user can still submit a solution to a problem with no data by sending the request themselves.

**Comment by quantum5** [comment]
Such a fitting issue number for the issue! Did you specifically wait for this?

**Comment by Xyene** [comment]
Of course ;)

**Comment by quantum5** [comment]
Hmm, I have a feeling this is not a real issue. Having a unjudgable submission is not a big deal with a bridge, and preventing yourself from submitting is a fitting punishment, don't you agree?

**Comment by quantum5** [comment]
Anyways, the reason this is not done is because a common case when test data does not exist for a problem is when the judge temporarily goes down. The user should be allowed to submit and let it be queued for some time. The UI change to prevent submission on the lack of judge is to prevent people from being confused.
