### ISSUE TITLE
Copy not Working

### ISSUE THREAD

**Issue by BinAccel** [DMOJ/site#410]
I tried to click copy to copy the sample data, but there is nothing on my clipboard. Using Firefox 46.0.1 on Windows 10 x64.

**Comment by Xyene** [comment]
Thanks for reporting; it's good to have an issue about this.

The cause of the issue is the library we use for clipboard managing, which [has a number of open issues regarding Firefox usage](https://github.com/zeroclipboard/zeroclipboard/issues?utf8=✓&q=is%3Aissue+is%3Aopen+firefox). We might be able to switch to something like [clipboard.js](https://github.com/zenorocha/clipboard.js/) so long as it doesn't have issues as well.

**Comment by Xyene** [comment]
@faiyaz26 has fixed this.
