### ISSUE TITLE
Gray and disable submit button if judge unavailable

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#460]
Save users a page load when all they'd be faced with is no judge.

**Comment by quantum5** [comment]
It is supposed to be a transient situation.

**Comment by Xyene** [comment]
It's oftentimes not, in practice. This change would save the frustration of writing a solution only to find there is no judge.

**Comment by Xyene** [comment]
![image](https://cloud.githubusercontent.com/assets/1403503/18258285/ab049d48-73a0-11e6-8402-f29536669dea.png)

Given

```css
    background: linear-gradient(to bottom,#888 0,#555 100%) repeat-x;
```

**Comment by quantum5** [comment]
Do not approve of this feature. There is a reason that there is a permission to change `is_public`, and that is to prevent publishing of problems without test data. A problem should be private if it does not have test data. Otherwise, it would be a transient situation and does not warrant the heavy-handed greyed button.
