### ISSUE TITLE
Allow people to view when users entered a contest

### ISSUE THREAD

**Issue by MarkThames** [DMOJ/site#476]
Otherwise, there is no way to tell if someone who has not yet submitted is still writing the contest, or how much time they have left (showing how much time is left would look odd since it's different and constantly changing throughout the ranking). The time could go under the user's name in small grey text, or, as @Xyene suggested, in a tooltip.

**Comment by Xyene** [comment]
I'm partial to the tooltip simply because ranking pages don't scale well on mobile as-is, and adding more info to them would only exacerbate the issue.

In a tooltip, however, we could probably display either (or both) time since start (e.g., _Started 50 minutes ago_) as well as a countdown timer for time remaining.

**Comment by Xyene** [comment]
This is done.
