### ISSUE TITLE
Markdown ruins latex

### ISSUE THREAD

**Issue by BinAccel** [DMOJ/site#482]
If markdown detects an empty new line in a `<latex>` tag while setting problems, it will treat it as a new paragraph, and the latex will not render properly.

**Comment by quantum5** [comment]
Just saying that this is unlikely to be fixed in a good way, or fixed at all, since the `markdown2` library is just a mess of regular expressions. We may be able to switch to a different library, but problem statements may be broken due to having a different set of quirks.

We may be able to swallow all double newlines in `<latex>` blocks, before passing to `markdown2`, but this is crazy.

TL;DR: don't expect this to be fixed very soon, and even if it is fixed, it will probably be ugly.

**Comment by Xyene** [comment]
Mistune (#509) respects glorious newlines in LaTeX.
