### ISSUE TITLE
Pretest visibility

### ISSUE THREAD

**Issue by dinoilic** [DMOJ/site#663]
Would it be possible to add a feature that shows pretests underneath the problem statement? I find it really tedious to copy and paste pretests to a problem statement and it's redundant in case I change pretests. It would be really nice if  there was an option to show them to the user.

**Comment by Xyene** [comment]
**Short version:** it'd be something useful to have, but not something we can hope to support at this time.

**Long version:**
This is something that we've considered doing before, but decided against due to the (not-obvious) complexity of doing so. I suppose I'll write some more details down for future reference, too.

The DMOJ site was originally designed to have no knowledge of problem data, and have judges simply let the site know which problem codes they were capable of grading (keeping data consistent between judges was/is the job of the sysadmin).

This gives a sysadmin a lot of flexibility in how to manage their data and syncing of it (NFS, SSHFS, etc.; OneDrive, Dropbox, rsync, and so on) that we wouldn't realistically be able to provide as part of this project. For example, on [dmoj.ca](https://dmoj.ca) where we we have tens of gigabytes of problem data, it doesn't make economical sense to provide so much storage to the webapp; problem data is instead distributed to judging servers via NFS off other servers in the background.

Site-managed data (#467, "Edit test data" link) is a relatively new feature:

> The site should be capable of managing a problem repository, allowing the data for certain problems to be managed on site. This would aid greatly in being able to allow more novice users to set problems, as well as not requiring sharing the problem repository with potentially untrusted users.

It doesn't scale well past a couple hundred problems, and often requires configuration of your nginx to allow big archives to be uploaded (i.e., uploading a 500mb IOI problem is out of the question with site-managed data).

Essentially, it's something we added to help ease in new users of the DMOJ platform, but there's a lot of things it doesn't/won't support (custom checkers, interactive problems, signature graded problems, dynamic keys in inits, etc.)

So, compatibility with statements written for non-site-managed problems is out of the question. But assuming that doesn't matter, there are other blockers:
* problem archives can't be decompressed and read for pretests on each problem load (too slow), so we'd have to either
    * commit pretests to the database whenever they are changed (bloat)
    * decompress archive and cache pretest data in memory like we do rendered markdown templates (tricky, very slow on first load)
* formatting:
    * ideally we'd have some sort of standard in how contests display pretests/samples, in practice there is none
    * many contests provide sample inputs that aren't part of the pretests, and vice-versa (defeating this feature entirely)
    * as a result this isn't something we'd be able to run on [dmoj.ca](https://dmoj.ca) without rewriting > 1500 problems, so it'd be very likely to break to due lack of maintenance

Anyway, hopefully that gives a general idea of why it's unlikely something like this (or anything that requires tight coupling between problem data and the site frontend) can't be implemented anytime soon.

**Comment by dinoilic** [comment]
Thanks for the explanation! It makes much more sense now that I know how it all works :smile:
