### ISSUE TITLE
Per-language time and memory limit

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#72]
We can add a `LanguageLimit` model to store per language time and memory limits. This model would be added as an inline to allow such configuration.

/cc @Xyene @FatalEagle

**Comment by FatalEagle** [comment]
Should be added as an override of the default time limit?

**Comment by quantum5** [comment]
Yes it would a override.

**Comment by Xyene** [comment]
My two cents are to tab the memory and time limit fields, because otherwise way too much info would be contained on one line when we get around to implementing per-testcase TL/ML:
> Time limit: 10-15s*

Tabs would look nicer, taking advantage that not every language will have a custom limit. Something like `[ * ][Java][Python]` on the info-float would be good in my opinion (`*` for all).

**Comment by Xyene** [comment]
How would this look like on the Best submissions page?

**Comment by quantum5** [comment]
Well if you use a slow language you deserve to be sorted lower.

**Comment by Xyene** [comment]
That's not much of a step up from not being able to solve the problem in the first place.

On another note, perhaps we should have a view where best submissions are split up by language. Perhaps the Best Submissions page should be tabbed, by default displaying the mixed ranking. I recall someone requesting this.

Not sure how that would work with the pagination, though. Pagination in a tab sounds awful.

**Comment by quantum5** [comment]
This is implemented. Only some form of UI to show the limits is needed.

**Comment by Xyene** [comment]
Unfortunately the UI part is likely the hardest part. Ever done tabs that look *nice* and *wrap around in small spaces* nicely? In CSS/JS? I haven't, and I'm not too keen on bringing in another library for them.

**Comment by quantum5** [comment]
Considering #71, I am tempted to agree. I can't even get the sidebar to work nicely. Though github has been a sort of inspiration. Look at the side bar on this page.

**Comment by quantum5** [comment]
The sidebar now works perfectly, ready to be used for this.

**Comment by Xyene** [comment]
Thought about this a bit, and came up with this display:

![image](https://cloud.githubusercontent.com/assets/1403503/17351131/04aa8dec-58fa-11e6-9c29-42e77a796cfe.png)

Ideally we'd use common name if every language with that common name has the same limit, otherwise we'd split the limits up (e.g., "Java 7: 2.0s", "Java 8: 5.0s").

**Comment by quantum5** [comment]
This is implemented.

**Comment by Xyene** [comment]
Going to have to reopen this, for we should include this data in PDFs too (we specify base ML/TL, anyway).

**Comment by quantum5** [comment]
Very well, please design how it would look like.

**Comment by Xyene** [comment]
Forget it; that belongs in a separate ticket (totally forgot about it for months).
