### ISSUE TITLE
Contest ending at midnight should be one day on calendar

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#748]
Currently, if a contest ends on the midnight of the next day, the contest is treated as a two day contest, instead of a one day contest on the calendar. This is annoying.

**Comment by ApoapsisAlpha** [comment]
This does not seem like a bug since the calendar indicates the starting and ending dates of a contest. If a contest starts at midnight on one day and ends on the midnight of the next day, then displaying it as a contest which takes place on two different days is not technically inaccurate. If a user wanted the contest to display on one day of the calendar, they could simply end the contest at 11:59 PM rather than midnight.

**Comment by quantum5** [comment]
We have never defined exactly if the end time is included or excluded from the interval. I am leaning towards making the end time exclusive, since the math works out nicer that way. However, ending at "11:59 PM" is definitely not the desired workaround, since it ends a full minute before midnight.

**Comment by kiritofeng** [comment]
This code is currently in production.
