### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#96]
Refs #94, #54

**Comment by quantum5** [comment]
#95 too.

**Comment by Xyene** [comment]
The issue described in #84 still applies for Dolphin 10, a popular Android browser.

**Comment by Xyene** [comment]
@WallE256 suggests moving the problem info-float to below the problem on mobile, to save space. Sounds good to me!

**Comment by Xyene** [comment]
Perhaps something like this: 

![](https://sc-cdn.scaleengine.net/i/40701f7945373f396e1a9c944f85bffd.png)

**Comment by FatalEagle** [comment]
Okay how about you tell me this first: exactly who is going to code and submit on their phone?

**Comment by Xyene** [comment]
It's not about making the site usable on a phone. It's about making the
site usable in small browser windows, not necessarily those of phones.
Should people be penalized with obstructed text and terrible menus simply
because they choose to snap DMOJ to one side of their screen and their IDE
to the other?

**Comment by quantum5** [comment]
I think showing `info-float` above the problem contents is both better and easier to implement. The user would probably not read the entire problem statement before submitting after they read it already. A bunch of css rules will ensure it doesn't compete for screen width with the problem body.

I also suggest the home page be tabbed with JS, so that the stream and blog posts don't compete for screen width.

**Comment by Xyene** [comment]
This is far too broad a ticket, and is becoming too much like #205. The site in general works acceptably well on mobile, and improvements to specific pages can be tracked as separate issues.
